development:
  adapter: postgresql
  encoding: unicode
  database: facepalm_development

test:
  adapter: postgresql
  encoding: unicode
  database: facepalm_test

production:
  adapter: postgresql
  encoding: unicode
  database: facepalm_production